
// This file is part of the "edge" library, available at https://github.com/adigostin/edge
// Copyright (c) 2011-2020 Adi Gostin, distributed under Apache License v2.0.

#pragma once
#include <list>
#include <optional>
#include <typeindex>
#include <unordered_map>
#include <variant>

namespace edge
{
	// Note that this event system currently works only on a single thread;
	// don't try to do something with events on more than one thread.

	class event_manager
	{
		template<typename event_t, typename return_t, typename... args_t>
		friend class event_subscriber;

		template<typename event_t, typename... args_t>
		friend struct event;

		template<typename event_t, typename return_t, typename... args_t>
		friend struct cancelable_event;

		friend struct event_token;

		struct handler_t
		{
			void* callback;
			void* callback_arg;
		};

		std::unordered_map<std::type_index, std::list<handler_t>> handlers;

		// This is a stack of all invocations made by the application. We allocated its
		// elements in the processor's stack, and keep pointers to the first and last elements.
		// It's a stack because we need to allow the application to invoke events
		// recursively (i.e., from the handler of one event, the application is allowed
		// to invoke the same or other events, or to add handlers, or to remove handlers).
		//
		// Recursivity is a common requirement for events. We have recursivity, for example,
		// with Windows messages passed around as a specific event_t;
		// when the application does not understand a message, it will pass it to DefWindowProc,
		// which may translate it to another message and call the application message handler
		// recursively. The message handler will now invoke the same event_t recursively with
		// a second message - the one generated by DefWindowProc. This the is recursive invocation
		// part. Upon decoding the second message, the application code may even create or destroy
		// application components which - directly or indirectly - add or remove more handlers for
		// the same event_manager (same HWND) and same event_t.
		// 
		// Every time the application request us to invoke the handlers of an event
		// (see invoker::operator()), we add an element to this stack and start
		// looking for registered handlers in the "handlers" variable.
		// If one of the handlers we invoke calls our remove_handler()
		// function to remove a handler, this function removes the specified handler and
		// adjusts the indices in the stack as needed (decrements some of them).
		struct pending_invoke;

		struct handler_ref_t
		{
			// If non-null, the iterator is into the list of queued_adds of this invoke.
			// If null, the iterator is into the list of handlers from event_manager.
			pending_invoke* invoke;
			std::list<handler_t>::const_iterator handler_it;

			bool operator==(const handler_ref_t& other) const
			{
				// Need to implement this explicitly cause =default might generate something
				// that compares "handler_it" first, and if "invoke" is not the same we'd get
				// an assertion in the standard library code.
				return (this->invoke == other.invoke) && (this->handler_it == other.handler_it);
			}
		};

		pending_invoke* first_invoke = nullptr;
		pending_invoke* last_invoke = nullptr;

	public:
		~event_manager();

		bool has_handlers() const;

		template<typename event_t>
		bool has_handlers() const
		{
			auto id = std::type_index(typeid(event_t));
			auto it = handlers.find(id);
			return ((it != handlers.end()) && !it->second.empty());
		}
	
	private:
		std::optional<handler_ref_t> find_handler (std::type_index event_id, void* callback, void* callback_arg);

		void add_handler (std::type_index event_id, void* callback, void* callback_arg);
		void remove_handler (std::type_index event_id, void* callback, void* callback_arg);

		struct pending_invoke
		{
			event_manager& em;
			std::type_index const event_id;
			bool            const reverse_invoke;
			std::optional<handler_ref_t> next_handler; // std::nullopt - finished enumerating handlers
			std::list<handler_t> queued_add_handlers;
			pending_invoke*    next = nullptr;
			pending_invoke*    prev = nullptr;

		public:
			pending_invoke (event_manager& em, std::type_index event_id, bool reverse_invoke);
			~pending_invoke();

			void move_next();

		private:
			void move_next_forward();
			void move_next_backward();

			pending_invoke* find_invoke_with_queued_handlers_forward (pending_invoke* search_from) const;
			pending_invoke* find_invoke_with_queued_handlers_backward (pending_invoke* search_from) const;
		};
	};

	struct event_token
	{
		event_manager& em;
		std::type_index ti;
		void* callback;
		void* callback_arg;

		~event_token()
		{
			em.remove_handler (ti, callback, callback_arg);
		}
	};

	template<typename event_t, typename return_t, typename... args_t>
	class event_subscriber
	{
		using callback_t = return_t(*)(void*, args_t...);

		event_manager& _em;

	public:
		event_subscriber (event_manager* em)
			: _em(*em)
		{ }

		event_subscriber (event_manager& em)
			: _em(em)
		{ }

		event_subscriber (const std::shared_ptr<event_manager>& em)
			: _em(*em.get())
		{ }

		event_subscriber (const event_subscriber&) = delete;
		event_subscriber & operator= (const event_subscriber &) = delete;

		void add_handler (return_t(*callback)(void*, args_t...), void* callback_arg)
		{
			_em.add_handler (std::type_index(typeid(event_t)), reinterpret_cast<void*>(callback), callback_arg);
		}

		event_token add_auto_handler (return_t(*callback)(void*, args_t...), void* callback_arg)
		{
			_em.add_handler (std::type_index(typeid(event_t)), reinterpret_cast<void*>(callback), callback_arg);
			return event_token{ _em, std::type_index(typeid(event_t)), callback, callback_arg };
		}

		void remove_handler (return_t(*callback)(void*, args_t...), void* callback_arg)
		{
			_em.remove_handler (std::type_index(typeid(event_t)), reinterpret_cast<void*>(callback), callback_arg);
		}

	private:
		template<typename T>
		struct extract_class;

		template<typename C, class... A>
		struct extract_class<return_t(C::*)(A...)>
		{
			using class_type = C;
		};

		template<class target_class, return_t(target_class::*member_callback)(args_t...)>
		static return_t proxy (void* arg, args_t... args)
		{
			auto c = static_cast<target_class*>(arg);
			return (c->*member_callback)(std::forward<args_t>(args)...);
		}

		template<class target_class, return_t(target_class::*member_callback)(args_t...) const>
		static return_t proxy (void* arg, args_t... args)
		{
			auto c = static_cast<const target_class*>(arg);
			return (c->*member_callback)(std::forward<args_t>(args)...);
		}

	public:
		template<auto member_callback, typename class_type = extract_class<decltype(member_callback)>::class_type>
		std::enable_if_t<std::is_member_function_pointer_v<decltype(member_callback)>>
		add_handler (class_type* target)
		{
			static_assert(std::is_convertible_v<decltype(member_callback), return_t(class_type::*)(args_t...)>
				        || std::is_convertible_v<decltype(member_callback), return_t(class_type::*)(args_t...)const>
				, "types of parameters and/or return value don't match");
			add_handler (&event_subscriber::proxy<class_type, member_callback>, target);
		}

		template<auto member_callback, typename class_type = extract_class<decltype(member_callback)>::class_type>
		event_token add_auto_handler (class_type* target)
		{
			static_assert(std::is_convertible_v<decltype(member_callback), return_t(class_type::*)(args_t...)>
						|| std::is_convertible_v<decltype(member_callback), return_t(class_type::*)(args_t...)const>
				, "types of parameters and/or return value don't match");
			return add_auto_handler(&event_subscriber::proxy<class_type, member_callback>, target);
		}

		template<auto member_callback, typename class_type = extract_class<decltype(member_callback)>::class_type>
		std::enable_if_t<std::is_member_function_pointer_v<decltype(member_callback)>>
		remove_handler (class_type* target)
		{
			static_assert(std::is_convertible_v<decltype(member_callback), return_t(class_type::*)(args_t...)>
				        || std::is_convertible_v<decltype(member_callback), return_t(class_type::*)(args_t...)const>
				, "types of parameters and/or return value don't match");
			remove_handler (&event_subscriber::proxy<class_type, member_callback>, target);
		}
	};

	namespace detail
	{
		// This class may seem superfluous; the invoke function could have been a member of event_manager
		// and invocation code would have been shorter. That solution, however, would have broken Intellisense.
		// This class is what it takes to keep Intellisense running. The optimizer hopefully does away with all the clutter.
		class invoker_base
		{
		protected:
			// std::variant is not ideal performance-wise, but it keeps Intellisense working for the constructor of this class.
			std::variant<std::shared_ptr<event_manager>, event_manager*> const _em;

		public:
			// This constructor takes a std::shared_ptr and is useful when the application code
			// holds the event_manager in a shared_ptr because it needs its lifetime extended
			// until after all invocations finish executing.
			invoker_base (std::shared_ptr<event_manager> em)
				: _em(std::move(em))
			{ }

			invoker_base (event_manager& em)
				: _em(&em)
			{ }

			invoker_base(const invoker_base&) = delete;
		};
	}

	template<typename event_t, typename... args_t>
	struct event
	{
		using callback_t = void(*)(void*, args_t...);

		using subscriber = event_subscriber<event_t, void, args_t...>;

		class invoker : public detail::invoker_base
		{
			using detail::invoker_base::invoker_base;

			void invoke_internal(bool reverse_invoke, args_t... args) const
			{
				auto em = std::holds_alternative<event_manager*>(_em) ? std::get<event_manager*>(_em) : std::get<std::shared_ptr<event_manager>>(_em).get();
				auto pi = event_manager::pending_invoke(*em, std::type_index(typeid(event_t)), reverse_invoke);
				while (pi.next_handler)
				{
					auto& handler = *pi.next_handler->handler_it;
					pi.move_next();
					auto typed_cb = reinterpret_cast<callback_t>(handler.callback);
					typed_cb(handler.callback_arg, std::forward<args_t>(args)...);
				}
			}

		public:
			void invoke (args_t... args) const { invoke_internal(false, std::forward<args_t>(args)...); }
			
			void reverse_invoke (args_t... args) const { invoke_internal(true, std::forward<args_t>(args)...); }

			void invoke (bool reverse_invoke, args_t... args) const { invoke_internal(reverse_invoke, std::forward<args_t>(args)...); }
		};
	};

	// return_t needs to be a type that satisfies std::is_constructible_v<bool, return_t>, such as
	// std::optional<random_type> or std::unique_ptr<random_type>. The code in the invoker class below
	// calls these handlers one by one until one of them returns a value that evaluates to bool "true".
	// and then it returns that value without invoking any more handlers. If none of the handlers return
	// something that evaluates to bool "true", this function return a default-initialized value such as
	// std::nullopt or an empty std::unique_ptr. This kind of events are useful for example to pass
	// Windows-specific messages to whoever registered handlers for them.
	template<typename event_t, typename return_t, typename... args_t>
	struct cancelable_event
	{
		static_assert (std::is_constructible_v<bool, return_t>);

		using callback_t = return_t(*)(void*, args_t...);

		using subscriber = event_subscriber<event_t, return_t, args_t...>;

		class invoker : public detail::invoker_base
		{
			using detail::invoker_base::invoker_base;

			return_t invoke_internal (bool reverse_invoke, args_t... args) const
			{
				auto em = std::holds_alternative<event_manager*>(_em) ? std::get<event_manager*>(_em) : std::get<std::shared_ptr<event_manager>>(_em).get();
				auto pi = event_manager::pending_invoke(*em, std::type_index(typeid(event_t)), reverse_invoke);
				while (pi.next_handler)
				{
					auto& handler = *pi.next_handler->handler_it;
					pi.move_next();
					auto typed_cb = reinterpret_cast<callback_t>(handler.callback);
					auto res = typed_cb(handler.callback_arg, std::forward<args_t>(args)...);
					if (res)
						return res;
				}

				return { };
			}

		public:
			return_t invoke (args_t... args) const { return invoke_internal(false, std::forward<args_t>(args)...); }

			return_t reverse_invoke (args_t... args) const { return invoke_internal(true, std::forward<args_t>(args)...); }

			template<bool reverse_invoke>
			return_t invoke (args_t... args) const { return invoke_internal(reverse_invoke, std::forward<args_t>(args)...); }
		};
	};
}
